source 'http://rubygems.org'

gem 'sinatra'

# async wrappers
gem 'eventmachine'
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem 'em-synchrony',     :git => 'git://github.com/igrigorik/em-synchrony.git', :require => [
  'em-synchrony',
  'em-synchrony/em-http'
  ]

# async activerecord requires
gem 'mysqlplus',      :git => 'git://github.com/oldmoe/mysqlplus.git',        :require => 'mysqlplus'
# gem 'em-mysqlplus',   :git => 'git://github.com/igrigorik/em-mysqlplus.git'
# gem 'em-mysqlplus',   :git => 'git://github.com/tmm1/em-mysql.git'
gem 'em-mysqlplus'
gem 'async_sinatra'
gem 'thin'
gem 'unicorn'